name: Post to Pronto
on:
  pull_request:
    types: [opened, closed, reopened]
  pull_request_review:
    types: [submitted, edited]
jobs:
  post-to-pronto:
    runs-on: ubuntu-latest
    steps:
      - name: post-message
        uses: Hitlabs/pr-reviewer-pronto-notification-action@zack
        with:
          chat-id: ${{ secrets.PRONTO_CHAT_ID }}
          api-token: ${{ secrets.PRONTO_BOT_API_TOKEN }}